apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: orionxo/udagram-api-feed:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret
