apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
      name: http
  selector:
    app: reverseproxy
